version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      python: 3.8
    commands:
      - echo "Installing dependencies"
      - npm install
  pre_build:
    commands:
      - echo "Running pre-build tasks"
      - npm run lint
  build:
    commands:
      - echo "Building the application"
      - npm run build
  post_build:
    commands:
      - echo "Post-build tasks"
      - zip -r app.zip .
      - echo "Build artifacts zipped"

artifacts:
  files:
    - app.zip
  discard-paths: yes
  base-directory: build
